// react-project/src/layouts/authlayout/Layout.jsx
import Sidebar from "./Sidebar";
import Header from "./Header";
import Footer from "./Footer";
import { Children } from "react";

function index({children}) {
  import("../../assets/custom/castom.js");
  return (
    <>
    <div className="wrapper">
        <Sidebar/>

        <div className="mainbody">
            <Header/>

            <div className="content">
                {children}
            </div>
            <Footer/>
        </div>
    </div>
    </>
  )
}

export default index;

// vue-project/src/layouts/dashlayout/Layout.vue
<template>
    <div class="wrapper">
        <Sidebar/>
        <div class="mainbody">
            <Header/>
            <div class="content">
                <slot></slot>
            </div>
            <footer></footer>
        </div>
    </div>
</template>

<script setup>
    import Sidebar from './Sidebar.vue';
    import Header from './Header.vue';
</script>

<style lang="scss" scoped>

</style>
