// react-project/src/views/dashboard/Form.jsx
import { useEffect, useState } from "react"
import Input from "../../components/Input";
import Button from "../../components/Button";

function Form({updateData, existingData, editData}) {
    const [field, setField] = useState({id: "", email: "", mobile: ""});
    const [err, setErr] = useState({email: "", mobile: ""});

    const handleInput = (e) => {
        const { name, value } = e.target;
        setField({...field, [name]: value});
    };

    useEffect(() => {
        if (editData?.id) {
            setField({
                id: editData.id || "",
                email: editData.email || "",
                mobile: editData.mobile || ""
            });
        };
    },[editData]);

    const resetForm = () => {
        setField({id: "", email: "", mobile: ""});
        setErr({email: "", mobile: ""});
    };

    const formSubmit = (event) => {
        event.preventDefault();
        let er = 0;
        const newErrors = {};
        if (email == "" || email == null || email == 0) {
            er++;
            newErrors.email = "email required";
        } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){
            newErrors.email = "invalid email format";
        } else {
            newErrors.email = "";
        }

        if (mobile == "" || mobile == null) {
            er++;
            newErrors.mobile = "mobile required";
        } else {
            newErrors.mobile = "";
        }
        setErr(newErrors);

        if (er === 0) {
            if (editData?.id && field.id) {
                const updated = existingData.map((item) =>
                    item.id === editData.id ? { ...field } : item
                );
                localStorage.setItem("dashdatas", JSON.stringify(updated));
            } else {
                const newId = Date.now();
                const newEntry = {...field, id: newId};
                localStorage.setItem("dashdatas", JSON.stringify([newEntry, ...existingData]));
            }
            updateData();
            resetForm();
        }
    };
  return (
    <>
        <form onSubmit={formSubmit}>
            <div className="mb-3">
                <div className="row g-1">
                    <Input type="hidden" name="id" onChange={handleInput} value={field.id}/>
                    <div className="col-6">
                        <Input 
                        type="text" 
                        label="Email" 
                        id="email" 
                        weight="sm" 
                        focus="true"
                        must="true"
                        onChange={handleInput} 
                        err={err.email} 
                        value={field.email} 
                        name="email"/>
                    </div>
                    <div className="col-6">
                        <Input 
                        type="text" 
                        label="Mobile" 
                        id="mobile" 
                        weight="sm" 
                        must="true" 
                        onChange={handleInput} 
                        err={err.mobile} 
                        value={field.mobile} 
                        name="mobile"/>
                    </div>
                </div>
            </div>                     
            <Button label={field.id ? "Update" : "Submit"} type="submit" btnclass="me-2"/>
            <Button label="Reset" type="button" onClick={resetForm}/>
        </form>
    </>
  )
}

export default Form

// vue-project/src/views/users/Form.vue
<template>
    <form @submit.prevent="submitForm">
        <div class="mb-3">
            <div class="row g-1">
                <input type="hidden" v-model="field.id">
                <div class="col-6">
                    <Input type="text" id="email" label="Email" weight="sm" placeholder="Email..." v-model="field.email" :err="err.email" focus must />
                </div>
                <div class="col-6">
                    <Input type="text" id="mobile" label="Mobile" weight="sm" placeholder="Mobile..." v-model="field.mobile" :err="err.mobile" must />
                </div>
            </div>
        </div>                     
        <Button type="submit" :label="field.id ? 'Update' : 'Submit'"/>
        <Button type="button" label="Reset" class="ms-2" @click="resetForm" color="secondary"/>
    </form>
</template>

<script setup>
import { reactive, ref, toRef, watchEffect } from 'vue';
import { useDash } from '@/stores/dash';
import Input from '@/components/Input.vue';
import Button from '@/components/Button.vue';

const field = reactive({ id:'', email: '', mobile: ''});
const err = reactive({ email: '', mobile: ''});

const props = defineProps({
    isEdited: { type: Boolean },
    modify: { type: Object }
});
const isEdited = toRef(props.isEdited);


const id = ref(1);
const dash = useDash();

const resetForm = () => {
    field.id = field.email = field.mobile = err.email = err.mobile = "";
}

const submitForm = async () => {
    let er = 0;
    if (field.email == "" || field.email == null || field.email == 0) {
        er++;
        err.email = "email required";
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(field.email)){
        err.email = "invalid email format";
    } else {
        err.email = "";
    }

    if (field.mobile == "" || field.mobile == null) {
        er++;
        err.mobile = "mobile required";
    } else {
        err.mobile = "";
    }
    
    if (er == 0 && field.id) {
        const data = {
            id: field.id,
            email: field.email,
            mobile: field.mobile
        }
        
        await dash.update(data);
        resetForm();
    } else if (er == 0) {
        const data = {
            id: id.value++,
            email: field.email,
            mobile: field.mobile
        }
        await dash.create(data);
        resetForm();
    }
};

watchEffect(() => {
    if (props.isEdited) {
        field.id = props.modify?.id;
        field.email = props.modify?.email;
        field.mobile = props.modify?.mobile;
    }
});

</script>

<style lang="scss" scoped>

</style>
