// react-project/src/views/dashboard/TableData.jsx
import Button from "../../components/Button";
import Table from "../../components/Table";

function TableData({existingData, onModify, onDelete}) {
  return (
    <>
        <Table existingData={existingData} 
                tHead={<><th>#</th>
                        <th>Email</th>
                        <th>Mobile</th>
                        <th>Action</th>
                        </>}
                tBody={(dt) => (
                  <>
                    <td>{dt.id}</td>
                    <td>{dt.email}</td>
                    <td>{dt.mobile}</td>
                    <td className="text-center">
                        <div className="btn-group btn-group-sm" role="group" aria-label="Basic mixed styles example">
                            <Button 
                            type="button" 
                            color="warning"
                            icon="bi bi-pencil-square"
                            onClick={() => onModify(dt.id)}
                            />
                            <Button 
                            type="button" 
                            color="danger"
                            icon="bi bi-trash"
                            onClick={() => onDelete(dt.id)}/>
                        </div>
                    </td>
                </>
                )}>     
        </Table>
    </>
  )
}

export default TableData

// vue-project/src/views/users/Tabledata.vue
<template>
    <Table :data="props.store.filter(i => i !== null && i !== undefined)">
        <template #thead>
            <th>#</th>
            <th>Email</th>
            <th>Mobile</th>
            <th>Action</th>
        </template>
        <template #tbody="{td}">
            <td>{{ td.id }}</td>
            <td>{{ td.email }}</td>
            <td>{{ td.mobile }}</td>
            <td class="text-center">
                <div class="btn-group btn-group-sm" role="group" aria-label="Basic mixed styles example">
                    <button type="button" class="btn btn-warning" @click="dataModify(td.id)"><i class="bi bi-pencil-square"></i></button>
                    <button type="button" class="btn btn-danger" @click="dataDelete(td.id)"><i class="bi bi-trash"></i></button>
                </div>
            </td>
        </template>
    </Table>
</template>

<script setup>
import { useDash } from '@/stores/dash';
import Table from '@/components/Table.vue';

const props = defineProps({
    store: {type: [Object, Array]}
})

const dash = useDash();

const emit = defineEmits(['edit']);
const dataModify = (id) => emit('edit', id);

const dataDelete = async (id) => {
    await dash.remove(id);
};
</script>

<style lang="scss" scoped>

</style>
