// vue-project/src/components/Input.vue
<template>
    <label :for="$attrs.id" :class="`form-label col-form-label${$attrs.weight ? '-' + $attrs.weight : ''} position-relative`">
        <span>{{ $attrs.label }}</span>
        <div :class="props.must ? 'must' : 'd-none'"></div>
    </label>
    <input class="form-control shadow-none" v-model="model" v-bind="$attrs" :class="{['form-control' + ($attrs.weight ? '-' + $attrs.weight : '')] : $attrs.weight}">
    <div class="form-text text-danger fw-bold" style="font-size: 10px;">{{ props.err }}</div>
</template>

<script setup>
import { useAttrs, onMounted, nextTick } from 'vue';

defineOptions({ inheritAttrs: false });

const props = defineProps({
    focus: { type: Boolean },
    must: { type: Boolean },
    err: { type: String }
})
const $attrs = useAttrs();

const model = defineModel();

onMounted(() => { props.focus ? nextTick(() => document.querySelector(`#${$attrs.id}`).focus()) : false });
</script>

<style lang="scss" scoped>
.must::after{
    content: "*";
    position: absolute;
    top: 5px;
    right: -7.5px;
    color: red;
}
</style>

// react-project/src/components/Input.jsx
import { useEffect, useRef } from "react";
import './Input.css';

function Input({ ...props}) {
  const focusInput = useRef();
  useEffect(() => {
    props.focus && focusInput.current.focus()
  },[]);  
  return (
    <>
        <label htmlFor={props.id} className={`form-label col-form-label${props.weight ? '-' + props.weight : ''} position-relative`}>
            <span>{props.label}</span>
            <div className={props.must ? 'must' : 'd-none'} ></div>
        </label>
        <input 
        ref={focusInput}
        className={`form-control ${props.weight ? 'form-control-' + props.weight : ''} shadow-none`}
        {...props}/>
        <div className="form-text text-danger fw-bold" style={{fontSize: 10 + 'px'}}>{props.err}</div>
    </>
  )
};

export default Input;
